import React from 'react'
import { PageLayout } from '../components/PageLayout.jsx'
import { PixelCard } from '../components/PixelCard.jsx'
import { PixelButton } from '../components/PixelButton.jsx'
import { PixelToast } from '../components/PixelToast.jsx'
import { PixelRadio } from '../components/PixelRadio.jsx'
import { StepBar } from '../components/StepBar.jsx'
import { PixelSelect } from '../components/PixelSelect.jsx'
import { TrajectoryPointCard } from '../components/TrajectoryPointCard.jsx'
import './AssemblyModelPageView.css'

const steps = [
  { id: 'step-1', status: 'done', position: 'first', label: '', title: 'INSTALL' },
  { id: 'step-2', status: 'done', position: 'middle', label: '', title: 'TEST' },
  { id: 'step-3', status: 'active', position: 'middle', label: '', title: 'ASSEMBLY' },
  { id: 'step-4', status: 'pending_4', position: 'last', label: '', title: 'EXECUTE' },
]

function JogAxisControl({ label, onNegative, onPositive }) {
  return (
    <div className="assembly-jog-control flex items-center">
      <button
        type="button"
        onClick={onNegative}
        className="w-10 h-9 text-[18px] flex items-center justify-center"
      >
        ‹
      </button>
      <div className="flex-1 text-center px text-[12px]">{label}</div>
      <button
        type="button"
        onClick={onPositive}
        className="w-10 h-9 text-[18px] flex items-center justify-center"
      >
        ›
      </button>
    </div>
  )
}

function CollisionHintModal({
  hintType,
  hintStep,
  showWrongAnswerToast,
  selectedOption,
  onSelectOption,
  onClose,
  onConfirm,
}) {
  const isDirectionStepOne = hintType === 'direction' && hintStep === 1
  const isDirectionStepTwo = hintType === 'direction' && hintStep === 2
  const isSingularityHint = hintType === 'singularity'
  const expectedAnswer = isSingularityHint ? 'C' : isDirectionStepTwo ? 'A' : 'B'
  const canConfirm = selectedOption === expectedAnswer
  const shouldDisableConfirm = hintType === 'waypoint' ? false : !canConfirm
  const primaryLabel = isDirectionStepOne ? 'NEXT' : 'Confirm'
  const visual =
    hintType === 'waypoint'
      ? {
          alert: 'Collision occurred! Try to add more waypoints to avoid colliding with objects',
          lines: [
            'The TCP moves smoothly from one recorded point to the next',
            'With too few waypoints, the trajectory cannot avoid objects between the points',
            'collisions happen',
          ],
          illustrationTitle: 'Driving around a rock',
          caption:
            "Just like driving: when there's a big rock on the road, you adjust your route and go around it.",
        }
      : isDirectionStepOne
        ? {
            alert: 'Wrong Direction! You need to stop the robot immediately!',
            lines: [
              'Offsets are relative to the previous point, so a relative frame is required',
              'Using the base frame requires cumulative calculation',
              "If values don't match the frame, the point ends up in a different location",
            ],
            illustrationTitle: 'Two jogging styles',
            caption:
              '"Place at center" and "move forward by 10 cm" may end at the same point, but use different frames.',
          }
        : isDirectionStepTwo
          ? {
              alert: 'What should you do when the robot moves quickly in an unexpected direction?',
              lines: [
                'Press the E-stop button immediately',
                'The robot will cut power and stop moving',
                'After fixing the issue, restart and move it away manually',
              ],
              illustrationTitle: 'E-STOP button',
              caption:
                'When risk grows quickly, cutting power is the safest immediate action.',
            }
          : {
              alert: "The robot has reached a singularity. It can't move in this configuration.",
              lines: [
                'TCP motion is generated by robot joint movement',
                'At singularity, tiny TCP move requires extremely large joint speed',
                'Joint speed/angle limits are reached',
                'The robot loses motion capability in some direction',
              ],
              illustrationTitle: 'Stretched arm',
              caption:
                'When your arm is fully stretched, some directions become hard to move - same idea for robot singularity.',
            }
  const optionList = isSingularityHint
    ? [
        { value: 'A', label: 'A. The program crashed' },
        { value: 'B', label: 'B. The robot lost power' },
        {
          value: 'C',
          label: 'C. The robot lost motion capability in certain directions',
        },
      ]
    : hintType === 'waypoint'
      ? [
          { value: 'A', label: 'A. It replays the demonstrated path exactly' },
          {
            value: 'B',
            label: 'B. The TCP moves from one recorded point to the next smoothly, in order',
          },
          {
            value: 'C',
            label: 'C. The TCP automatically moves from the grab point to the drop point',
          },
        ]
      : isDirectionStepOne
        ? [
            { value: 'A', label: 'A. The offset value was wrong' },
            { value: 'B', label: 'B. The reference frame used for the offset was different' },
            { value: 'C', label: 'C. The robot speed was too high' },
          ]
        : [
            {
              value: 'A',
              label: 'A. Pausing may fail if communication is interrupted.',
            },
            { value: 'B', label: 'B. Pausing is slower' },
            { value: 'C', label: 'C. Pausing resets the robot' },
          ]

  return (
    <div className="assembly-hint-overlay fixed inset-0 z-50 flex items-center justify-center">
      <div className="assembly-hint-modal pixel-card soft-grid p-10">
        {showWrongAnswerToast && (
          <div className="assembly-wrong-answer-toast px text-[12px]">
            ⚠ Wrong answer
          </div>
        )}
        <div className="mb-8">
          <div className="assembly-hint-alert px text-[18px] mb-6 flex items-center">
            <span className="assembly-hint-icon">💡</span>
            {visual.alert}
          </div>

          <div className="flex justify-between items-start gap-8">
            <div className="flex-1">
              <div className="assembly-hint-copy text-[20px] flex flex-col items-center gap-2 text-center">
                <div>{visual.lines[0]}</div>
                <div className="assembly-hint-arrow px">↓</div>
                <div>{visual.lines[1]}</div>
                <div className="assembly-hint-arrow px">↓</div>
                <div>{visual.lines[2]}</div>
                {visual.lines[3] ? (
                  <>
                    <div className="assembly-hint-arrow px">↓</div>
                    <div>{visual.lines[3]}</div>
                  </>
                ) : null}
              </div>
            </div>

            <div className="assembly-hint-illustration pixel-card soft-grid">
              <div className="flex flex-col w-full h-full">
                <div className="flex-1 overflow-hidden flex items-center justify-center mb-2">
                  <div className={`w-full h-full flex flex-col items-center justify-center text-center ${isSingularityHint ? 'assembly-singularity-illustration' : ''}`}>
                    <div className="text-[28px] mb-3">Illustration</div>
                    <div className="text-[26px]">{visual.illustrationTitle}</div>
                  </div>
                </div>
                <div className="assembly-hint-caption text-[13px]">
                  {visual.caption}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="assembly-hint-divider mb-4" />

        <div className="text-[24px] mb-4">
          {hintType === 'waypoint' &&
            '🤔 Question: How does the robot follow a planned trajectory during execution?'}
          {isDirectionStepOne &&
            '🤔 Question: Why did the point move to a completely different position?'}
          {isDirectionStepTwo &&
            '🤔 Question: Why is pressing E-stop necessary instead of just pausing the program?'}
          {isSingularityHint &&
            '🤔 Question: Why does the robot stop moving at a singularity?'}
        </div>

        <div className="space-y-3 text-[14px]">
          {optionList.map((option) => (
            <PixelRadio
              key={option.value}
              label={option.label}
              checked={selectedOption === option.value}
              onChange={() => onSelectOption(option.value)}
            />
          ))}
        </div>

        <div className="mt-8 flex gap-4">
          {!isDirectionStepTwo && (
            <PixelButton
              variant="white"
              className="px-8 py-4 text-[12px]"
              onClick={onClose}
            >
              Close
            </PixelButton>
          )}
          <PixelButton
            variant="magenta"
            className={`flex-1 py-4 text-[12px] ${
              shouldDisableConfirm ? 'opacity-40 pointer-events-none' : ''
            }`}
            disabled={shouldDisableConfirm}
            onClick={onConfirm}
          >
            {primaryLabel}
          </PixelButton>
        </div>
      </div>
    </div>
  )
}

export function AssemblyModelPageView({
  stage,
  mode,
  grab,
  grabFrame,
  drop,
  dropFrame,
  waypoints,
  frameOptions,
  jogFrameOptions,
  canConfirm,
  isAssemblyRunning,
  hasCollision,
  showCollisionToast,
  showWrongAnswerToast,
  showCollisionHintModal,
  selectedCollisionOption,
  collisionHintType,
  collisionHintStep,
  showRelativeHintInfo,
  showSuccessModal,
  successPrimaryLabel,
  jogFrame,
  hasSingularityWarning,
  connectionInfo,
  onToggleMode,
  onConfirmTest,
  onNextBlock,
  onSuccessPrimaryAction,
  onTryAgainCurrentBlock,
  onOpenCollisionHint,
  onCloseCollisionHint,
  onSelectCollisionOption,
  onConfirmCollisionHint,
  onAddWaypoint,
  onRemoveWaypoint,
  onChangeGrabAxis,
  onChangeGrabFrame,
  onChangeDropAxis,
  onChangeDropFrame,
  onChangeWaypointAxis,
  onChangeWaypointFrame,
  onChangeJogFrame,
  onJogMove,
  onRecordGrab,
  onRecordDrop,
  onRecordWaypoint,
  showAddWaypoint = true,
}) {
  // Keep a unified initial layout across all assembly blocks.
  const showJoggingPanel = false
  const isThirdBlock = stage === 'third-block'
  const confirmButtonLabel = hasSingularityWarning ? 'Reset the robot' : 'Confirm & Test'

  return (
    <PageLayout>
      <div className="flex items-center justify-between shrink-0 mb-10">
        <div className="assembly-page-title px text-[24px]">
          Lion Model Assembly Game
        </div>
        <div className="flex items-center gap-3">
          <div className="connection-pill px text-[9px] px-2 py-2">
            {connectionInfo}
          </div>
          <div className="swatch" style={{ background: 'var(--bgPurple)' }} />
          <div className="swatch" style={{ background: 'var(--orange)' }} />
          <div className="swatch" style={{ background: 'var(--magenta)' }} />
        </div>
      </div>

      <StepBar steps={steps} />

      <PixelToast
        open={showCollisionToast}
        icon="⚠"
        message="Collision occurred! Try to solve it"
      />

      <div className="grid lg:grid-cols-[4fr_3fr] gap-8 flex-1 min-h-0 max-lg:grid-rows-[minmax(0,1fr)_minmax(0,1fr)]">
        <PixelCard
          padding="p-6"
          className="min-h-0 max-h-full flex flex-col overflow-hidden"
        >
          <div className="flex-1 min-h-0 overflow-y-auto flex flex-col gap-4 pr-4 pb-6">
            <div className="assembly-intro assembly-intro-prominent assembly-trajectory-title text-[20px] leading-[1.2] font-bold">
              Drag the robot&apos;s end effector to teach it where to pick and place the
              block.
            </div>

            {showJoggingPanel ? (
              <div
                className={`pixel-card soft-grid mt-2 p-3 ${
                  hasSingularityWarning ? 'assembly-danger-shell' : ''
                }`}
                style={{ background: 'var(--panel)' }}
              >
                <div className="flex items-center justify-between gap-4 mb-2">
                  <div className="assembly-ink text-[22px]">
                    Jogging
                  </div>
                  <PixelSelect
                    className="w-[220px]"
                    value={jogFrame}
                    onChange={onChangeJogFrame}
                    options={jogFrameOptions}
                    variant="flat"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <JogAxisControl
                    label="X"
                    onNegative={() => onJogMove('x', 'negative')}
                    onPositive={() => onJogMove('x', 'positive')}
                  />
                  <JogAxisControl
                    label="Z"
                    onNegative={() => onJogMove('z', 'negative')}
                    onPositive={() => onJogMove('z', 'positive')}
                  />
                  <JogAxisControl
                    label="Y"
                    onNegative={() => onJogMove('y', 'negative')}
                    onPositive={() => onJogMove('y', 'positive')}
                  />
                  <JogAxisControl
                    label="Rx"
                    onNegative={() => onJogMove('rx', 'negative')}
                    onPositive={() => onJogMove('rx', 'positive')}
                  />
                </div>
              </div>
            ) : null}

            <PixelCard
              padding="p-4"
              className={`flex-1 min-h-0 overflow-visible assembly-trajectory-shell ${
                hasSingularityWarning ? 'assembly-danger-shell' : ''
              }`}
            >
              <div
                className="assembly-trajectory-scroll flex-1 min-h-0 overflow-y-auto flex flex-col gap-3"
              >
                <TrajectoryPointCard
                  accent="magenta"
                  title="Pick Point"
                  point={grab}
                  frameOptions={frameOptions}
                  frameValue={grabFrame}
                  onFrameChange={onChangeGrabFrame}
                  onAxisChange={onChangeGrabAxis}
                  onRecord={onRecordGrab}
                />

                {waypoints.map((waypoint) => (
                  <TrajectoryPointCard
                    key={waypoint.id}
                    accent="orange"
                    title="WayPoint"
                    point={waypoint.point}
                    frameOptions={frameOptions}
                    frameValue={waypoint.frame}
                    onFrameChange={(value) =>
                      onChangeWaypointFrame(waypoint.id, value)
                    }
                    onAxisChange={(axis, value) =>
                      onChangeWaypointAxis(waypoint.id, axis, value)
                    }
                    onRecord={() => onRecordWaypoint(waypoint.id)}
                    onRemove={() => onRemoveWaypoint(waypoint.id)}
                  />
                ))}

                {showAddWaypoint && (
                  <div className="flex justify-center my-2">
                    <button
                      type="button"
                      onClick={onAddWaypoint}
                      className="w-8 h-8 rounded-full border-2 border-[var(--ink)] flex items-center justify-center text-[18px]"
                      style={{ background: 'var(--panel)' }}
                      aria-label="Add waypoint"
                    >
                      +
                    </button>
                  </div>
                )}

                <TrajectoryPointCard
                  accent="green"
                  title="Drop Point"
                  point={drop}
                  frameOptions={frameOptions}
                  frameValue={dropFrame}
                  onFrameChange={onChangeDropFrame}
                  onAxisChange={onChangeDropAxis}
                  onRecord={onRecordDrop}
                  bordered={false}
                />
              </div>
            </PixelCard>
          </div>

          <div className="mt-4 flex items-center gap-4">
            {isAssemblyRunning ? (
              <div
                className="assembly-running-shell w-full"
              >
                <div className="running-bar assembly-running-fill" />
                <span className="assembly-running-label px text-[13px]">
                  Running...
                </span>
              </div>
            ) : (
              <>
                <PixelButton
                  variant="white"
                  className={`assembly-mode-pixel-btn py-4 px-8 text-[14px] ${
                    mode === 'pick' ? 'assembly-mode-btn-pick' : 'assembly-mode-btn-drop'
                  }`}
                  onClick={onToggleMode}
                >
                  {mode === 'pick' ? 'Pick' : 'Drop'}
                </PixelButton>
                <PixelButton
                  variant="magenta"
                  className={`flex-1 py-4 text-[12px] ${
                    !canConfirm ? 'opacity-40 pointer-events-none' : ''
                  }`}
                  disabled={!canConfirm}
                  onClick={onConfirmTest}
                >
                  {confirmButtonLabel}
                </PixelButton>
              </>
            )}
          </div>
        </PixelCard>

        <PixelCard
          title="3D ROBOT MODEL"
          titleColor="var(--orange)"
          className="min-h-0 max-h-full flex flex-col overflow-hidden"
        >
          <div
            className="assembly-model-stage flex-1 min-h-0 overflow-y-auto flex items-center justify-center"
          >
            <div className="relative w-full h-full flex items-center justify-center py-16">
              <div className="text-center">
                <div className="px text-[16px] mb-2">Lion Model</div>
                <div className="assembly-muted px text-[12px]">
                  {isThirdBlock
                    ? 'Install the third building block'
                    : 'Install the first building block'}
                </div>
                {isThirdBlock && (
                  <div className="assembly-third-coordinate mt-5">
                    <div>World</div>
                    <div>Flange</div>
                    <div>TCP</div>
                  </div>
                )}
                {showRelativeHintInfo && (
                  <div className="assembly-relative-box mt-5">
                    <div className="assembly-relative-title">
                      Maybe you need add some intermediate waypoint
                    </div>
                    <div className="assembly-relative-subtitle">
                      Highlight the relative offset
                    </div>
                    <div className="assembly-relative-lines">
                      <div>Y: 60mm</div>
                      <div>Z: 20mm</div>
                      <div>Y: 20mm</div>
                    </div>
                    <div className="assembly-relative-note">
                      Add intermediate waypoints and align values with selected
                      reference frame.
                    </div>
                  </div>
                )}
              </div>
              {isThirdBlock && hasSingularityWarning && (
                <div className="assembly-singularity-warning assembly-singularity-warning-top">
                  You can move the block to avoid the singularity on the trajectory.
                </div>
              )}

              {hasCollision && !isAssemblyRunning && (
                <button
                  type="button"
                  onClick={onOpenCollisionHint}
                  style={{
                    position: 'absolute',
                    right: '24px',
                    bottom: '24px',
                    width: '60px',
                    height: '60px',
                    borderRadius: '9999px',
                    border: '2px solid var(--ink)',
                    boxShadow: '4px 4px 0 var(--shadow)',
                    background: '#FFD5D5',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  <span
                    style={{
                      fontSize: '26px',
                      textShadow: '2px 2px 0 var(--shadow)',
                    }}
                  >
                    💡
                  </span>
                </button>
              )}
            </div>
          </div>
        </PixelCard>
      </div>

      {showSuccessModal && (
        <div
          className="assembly-modal-overlay fixed inset-0 z-50 flex items-center justify-center"
        >
          <div className="w-full max-w-xl px-6">
            <div className="text-center">
              <div className="assembly-modal-gif mx-auto mb-6 flex items-center justify-center">
                <img
                  className="assembly-modal-gif-image"
                  src="/placeholders/celebration-gif.gif"
                  alt="Celebration gif"
                />
              </div>
              <div className="assembly-success-text px text-[20px] mb-3">
                Assembly complete!
              </div>
              <div className="assembly-success-text px text-[20px] mb-8">
                NEXT LEVEL UNLOCKED!
              </div>
              <div className="flex items-center gap-4">
                <PixelButton
                  variant="white"
                  className="px-8 py-5 text-[12px]"
                  onClick={onTryAgainCurrentBlock}
                >
                  Try again
                </PixelButton>
                <PixelButton
                  variant="magenta"
                  className="flex-1 py-5 text-[14px]"
                  onClick={onSuccessPrimaryAction ?? onNextBlock}
                >
                  {successPrimaryLabel ?? 'Next block'}
                </PixelButton>
              </div>
            </div>
          </div>
        </div>
      )}

      {showCollisionHintModal && (
        <CollisionHintModal
          hintType={collisionHintType}
          hintStep={collisionHintStep}
          showWrongAnswerToast={showWrongAnswerToast}
          selectedOption={selectedCollisionOption}
          onSelectOption={onSelectCollisionOption}
          onClose={onCloseCollisionHint}
          onConfirm={onConfirmCollisionHint}
        />
      )}
    </PageLayout>
  )
}
